# Generated by Django 5.1.4 on 2025-05-30 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_landproperty_land_record_alter_landproperty_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ganache_address',
        ),
    ]
